mdapi_output_dir/objects/Car_Part__c.object
<CustomObject>
    <label>Car Part</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Car Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Container__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container</label>
        <referenceTo>Container__c</referenceTo>
        <relationshipLabel>Car Parts</relationshipLabel>
        <relationshipName>Car_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Export__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Export</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

mdapi_output_dir/objects/Container__c.object
<CustomObject>
    <label>Container</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Container Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/services/CarPartService.cls
public with sharing class CarPartService {
    public static void makeContainerTrue(List <Car_Part__c> carPartNewList) {
            
         /*List<Car_Part__c> carPartsToUpdate =[Select Id, Name from Car_Part__c];*/

          for (Car_Part__c carPart : carPartNewList)  {
        // Check if the container field is selected (assuming 'Container__c' is the API name of the container field)
        if (carPart.Container__c != null) {
            // Set the isExport field to true (assuming 'isExport__c' is the API name of the isExport field)
            carPart.Is_Export__c = true;
            /*carPartsToUpdate.add(carPart);*/
        }
    }    /*// Update the records with the updated 'isExport' field value
    update carPartsToUpdate;*/
}
}