mdapi_output_dir/objects/Car__c.object
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Driver__c</fullName>
        <label>Driver</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cars</relationshipLabel>
        <relationshipName>Cars</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapi_output_dir/objects/Car_Part__c.object
<CustomObject>
    <label>Car Part</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Car Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Car__c</fullName>
        <label>Car</label>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Car Parts</relationshipLabel>
        <relationshipName>Car_Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Container__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container</label>
        <referenceTo>Container__c</referenceTo>
        <relationshipLabel>Car Parts</relationshipLabel>
        <relationshipName>Car_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapi_output_dir/objects/Container__c.object
<CustomObject>
    <label>Container</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Container Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Containers</relationshipLabel>
        <relationshipName>Containers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/classes/services/CarPartServiceTest.cls
@IsTest(SeeAllData=false)
private class CarPartServiceTest {

    /**
     *Test class: Write the trigger when Account inserrted with Type='Hot', create the task to owner
     *  Class: insertTaskToOwner
     * @author Adina
     */       
 @testSetup
 public static void collectData(){
     Account acc = new Account(name = 'testAccount');
     insert acc;
     
     acc = [Select id from Account];
     
     Contact con =  new Contact(lastName = 'testContact');
     insert con;
     
     con = [Select id from Contact];
     
     Car__c car = new Car__c(name = 'testCar', driver__c = con.id);
     insert car;
     
     Container__c cont = new Container__c(account__c = acc.id);
     insert cont;        
     
 }
 
 @isTest
 public static void testScenario(){
     
     Container__c cont = [Select id, name from Container__c];
     
     Car__c car = [Select id from Car__c];
     
     Car_part__c carp = new Car_part__c(container__c = cont.id, car__c = car.id);
     insert carp;
     
     List<EmailMessage> emails = [SELECT Id FROM EmailMessage];
     
     System.assertNotEquals(0, emails.size());
 }