mdapi_output_dir/objects/Car__c.object
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Car_Cost__c</fullName>
        <label>Car Cost (in USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Comission__c</fullName>
        <label>Comission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Driver__c</fullName>
        <label>Driver</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cars</relationshipLabel>
        <relationshipName>Cars</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapi_output_dir/objects/Car_Part__c.object
<CustomObject>
    <label>Car Part</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Car Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Car__c</fullName>
        <label>Car</label>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Car Parts</relationshipLabel>
        <relationshipName>Car_Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Container__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container</label>
        <referenceTo>Container__c</referenceTo>
        <relationshipLabel>Car Parts</relationshipLabel>
        <relationshipName>Car_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Export__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Export</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

mdapi_output_dir/objects/Container__c.object
<CustomObject>
    <label>Container</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Container Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Containers</relationshipLabel>
        <relationshipName>Containers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/classes/CarPartTriggerTest.cls
/**
 * Created by omurzakov on 20.08.2022.
 */

@isTest
private class CarPartTriggerTest {
    @isTest
    static void testTriggerOnInsert() {
        // Create a new car part with the container selected
       
        
        Account acc=new Account(Name='Japarov');
        insert acc;
        contact con=new Contact(LastName='Japarov');
        insert con;
        Car__c car = new Car__c(Name = 'Test Car', Car_Cost__c = 20000, Comission__c = 18000, Driver__c=con.Id);
        insert car;
        Container__c cont=new Container__c(Account__c=acc.Id);
        insert cont;
            
        Car_Part__c carPart = new Car_Part__c(Is_Export__c= true, Container__c=cont.Id,Car__c=car.Id);

        // Insert the test data
        
        insert carPart;
        

        // Retrieve the updated record to verify the change
        carPart = [SELECT Id, Name, Is_Export__c FROM Car_Part__c WHERE Id = :carPart.Id];

        // Assertions
        System.assertEquals(true, carPart.Is_Export__c, 'isExport should be true for the inserted record');
    }
}