mdapi_output_dir/objects/Car__c.object
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Distance__c</fullName>
        <label>Distance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Paid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Paid</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/classes/CarController1.cls
public with sharing class CarController1 {
    @AuraEnabled(cacheable=true)
    public static List<Car__c> getCarsByName(String carName) {
        String searchTerm = '%' + carName + '%';
        return [SELECT Name, Distance__c, Is_Paid__c FROM Car__c WHERE Name LIKE :searchTerm];
    }
}

/*public with sharing class accountInsertController {

@AuraEnabled

public static id createAccount(String accName, String accPhone){

    Account acc = new Account (Name=accName, Phone=accPhone);

    insert acc;

    return acc.id;

 }

}*/